### ISSUE TITLE
Links are not redirected properly

### ISSUE THREAD

**Issue by lautarobock** [yegor256/netbout#668] opened 2015-06-04 14:37 UTC
If you go to netbout **agenda** page and make click on any github bug, you cannot get the page, instead of it, you get an URL like this: http://www.netbout.com/b/[https://github.com/yegor256/takes/issues/263](https://github.com/yegor256/takes/issues/263)

**Comment by dmzaytsev** [comment] 2015-06-04 15:36
@lautarobock it's a duplicate of #664

**Comment by lautarobock** [comment] 2015-06-04 15:42
@dmzaytsev yes, I've see it later,

**Comment by dmzaytsev** [comment] 2015-06-05 15:26
@lautarobock please close this ticket

**Closed** 2015-06-05 15:29 UTC
