### ISSUE TITLE
Stack Trace. 

### ISSUE THREAD

**Issue by techartist** [yegor256/netbout#1053] opened 2016-02-26 17:02 UTC
java.lang.IllegalStateException: [GET http://www.netbout.com/?PsByFlag=PsGoogle&code=4%2Fw6fusCi9LOJMOB56qKNFo3BkByN-VjU1Wxt5-9ks6mU&state=http%3A%2F%2Fwww.netbout.com%2F] failed in 369ms: null
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:112)
    at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:54)
    at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:66)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.flash.TkFlash.act(TkFlash.java:106)
    at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.http.BkBasic.print(BkBasic.java:100)
    at org.takes.http.BkBasic.accept(BkBasic.java:78)
    at org.takes.http.BkSafe$1.accept(BkSafe.java:51)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkTimeable$BkThreads.accept(BkTimeable.java:106)
    at org.takes.http.BkWrap.accept(BkWrap.java:52)
    at org.takes.http.BkParallel$1$1.run(BkParallel.java:89)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:199)
    at org.takes.facets.auth.social.PsGoogle.parse(PsGoogle.java:199)
    at org.takes.facets.auth.social.PsGoogle.fetch(PsGoogle.java:151)
    at org.takes.facets.auth.social.PsGoogle.enter(PsGoogle.java:129)
    at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:107)
    at org.takes.facets.auth.PsChain.enter(PsChain.java:70)
    at com.netbout.rest.PsTwice.enter(PsTwice.java:70)
    at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
    at org.takes.tk.TkWrap.act(TkWrap.java:61)
    at org.takes.facets.forward.TkForward.act(TkForward.java:68)
    at org.takes.facets.fallback.TkFallback.route(TkFallback.java:85)
    ... 22 more

**Comment by dmzaytsev** [comment] 2016-02-26 17:13
@techartist thanks for reporting 
we have ticket  #1038 for this case

**Comment by dmzaytsev** [comment] 2016-03-07 07:50
@karato this is duplicate of #1038

**Closed** 2024-01-22 12:39 UTC
