### ISSUE TITLE
Errors on production when trying to upload files

### ISSUE THREAD

**Issue by mkordas** [yegor256/netbout#861] opened 2015-12-11 23:53 UTC
I was playing with production instance of Netbout and while adding attachment to the bout (3 MB TXT file) I get the following stacktrace displayed:
```
java.io.IOException: Too many open files
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at java.io.File.createTempFile(File.java:1989)
	at java.io.File.createTempFile(File.java:2040)
	at org.takes.rq.RqMultipart$Base.make(RqMultipart.java:235)
	at org.takes.rq.RqMultipart$Base.buildRequests(RqMultipart.java:222)
	at org.takes.rq.RqMultipart$Base.(RqMultipart.java:140)
	at com.netbout.rest.bout.TkAttach.act(TkAttach.java:94)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

After pressing back the following stacktraces were shown:
```
java.io.IOException: com.amazonaws.AmazonClientException: Unable to execute HTTP request: dynamodb.us-east-1.amazonaws.com: System error
	at com.jcabi.dynamo.AwsItem.put_aroundBody6(AwsItem.java:211)
	at com.jcabi.dynamo.AwsItem$AjcClosure7.run(AwsItem.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.jcabi.dynamo.AwsItem.put(AwsItem.java:192)
	at com.netbout.dynamo.DyAlias.photo_aroundBody6(DyAlias.java:111)
	at com.netbout.dynamo.DyAlias$AjcClosure7.run(DyAlias.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.dynamo.DyAlias.photo(DyAlias.java:111)
	at com.netbout.cached.CdAlias.photo_aroundBody12(CdAlias.java:90)
	at com.netbout.cached.CdAlias$AjcClosure13.run(CdAlias.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.cached.CdAlias.photo(CdAlias.java:90)
	at com.netbout.email.EmAlias.photo_aroundBody6(EmAlias.java:108)
	at com.netbout.email.EmAlias$AjcClosure7.run(EmAlias.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:207)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
	at com.netbout.email.EmAlias.photo(EmAlias.java:108)
	at com.netbout.rest.RqAlias.alias(RqAlias.java:127)
	at com.netbout.rest.bout.RqBout.bout(RqBout.java:75)
	at com.netbout.rest.bout.TkIndex.act(TkIndex.java:80)
	at com.netbout.rest.bout.FkBout$3.act(FkBout.java:111)
	at com.netbout.rest.bout.FkBout$2.act(FkBout.java:89)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at com.netbout.rest.bout.FkBout.route(FkBout.java:81)
	at com.netbout.rest.bout.FkBout.access$000(FkBout.java:52)
	at com.netbout.rest.bout.FkBout$1.route(FkBout.java:65)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.fork.FkRegex$1.act(FkRegex.java:152)
	at org.takes.facets.fork.FkRegex.route(FkRegex.java:189)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at com.netbout.rest.FkRegistered$1.route(FkRegistered.java:70)
	at org.takes.facets.fork.FkWrap.route(FkWrap.java:61)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.fork.FkAuthenticated.route(FkAuthenticated.java:82)
	at org.takes.facets.fork.TkFork.act(TkFork.java:101)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:109)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:89)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.forward.TkForward.act(TkForward.java:68)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:80)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:50)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:62)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:100)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:67)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:72)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:71)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.tk.TkWrap.act(TkWrap.java:61)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.AmazonClientException: Unable to execute HTTP request: dynamodb.us-east-1.amazonaws.com: System error
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:471)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:295)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:3116)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.updateItem(AmazonDynamoDBClient.java:1322)
	at com.jcabi.dynamo.AwsItem.put_aroundBody6(AwsItem.java:203)
	... 72 more
Caused by: java.net.UnknownHostException: dynamodb.us-east-1.amazonaws.com: System error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1246)
	at java.net.InetAddress.getAllByName(InetAddress.java:1162)
	at java.net.InetAddress.getAllByName(InetAddress.java:1098)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:304)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:685)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:460)
```

This made entire application down:
![image](https://cloud.githubusercontent.com/assets/5467276/11758389/b04220f0-a06a-11e5-9ad6-41fb3251d84e.png)

It must be some kind of bug, but I'm not sure what is exactly the root cause.

**Comment by dmzaytsev** [comment] 2015-12-12 07:29
@mkordas is this issue reproducible ?

**Comment by mkordas** [comment] 2015-12-12 21:19
@dmzaytsev yes, just try to attach this large [TXT file](https://drive.google.com/file/d/0BwYOBDbn-h3fX1ZHVmJJdDhPMy13Y1N3Nlh2OW5JVGxJNUlZ) to any bout on production instance

**Comment by dmzaytsev** [comment] 2015-12-13 05:14
@karato it's a valid bug

**Comment by karato** [comment] 2015-12-13 09:18
> @karato it's a valid bug

@dmzaytsev added "bug" tag to this issue

**Comment by karato** [comment] 2015-12-13 10:27
@mkordas I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment] 2015-12-13 13:06
@mkordas many thanks, **15 mins** added to your acc for reporting this bug, pmt ID `566d6d668d888545d1000129`

**Comment by exper0** [comment] 2016-01-15 15:53
@dmzaytsev @mkordas I'm pretty sure it's fixed in scope of #868

**Comment by dmzaytsev** [comment] 2016-01-15 16:02
@exper0 I just tried to upload the file https://github.com/yegor256/netbout/issues/861#issuecomment-164194700
and got a stack trace

**Comment by exper0** [comment] 2016-01-15 16:08
@dmzaytsev do we have #861 deployed in production? I know it's merged and deployed somewhere but I guess not in production

**Comment by dmzaytsev** [comment] 2016-01-15 16:19
@exper0 you're right it not in production yet
but I also checked on snapshot.netbout.com with same result

**Comment by exper0** [comment] 2016-01-15 16:45
@dmzaytsev you're right, thanks. Anyway it's very similar issue and will be fixed https://github.com/yegor256/takes/issues/512 is fixed. I'll let you know once it's happened.

**Comment by exper0** [comment] 2016-01-15 22:23
@dmzaytsev so I think this issue should be postponed until https://github.com/yegor256/takes/issues/512 is fixed. Btw, it's very common problem overall both in Takes and in Netbout(both in tests and actualy code) - files often not closed causing issues like above

**Comment by exper0** [comment] 2016-01-18 14:09
@dmzaytsev found similar issue in Takes: https://github.com/yegor256/takes/issues/254

**Comment by karato** [comment] 2016-02-20 20:57
@carlosgines can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by CarlosGines** [comment] 2016-02-21 23:49
Ok, thank you @karato

**Comment by CarlosGines** [comment] 2016-02-22 17:11
I have created issue #1033 that needs to be addressed before I can continue with this task. Waiting for its approval.

**Comment by CarlosGines** [comment] 2016-02-26 19:39
@karato It looks like this issue comes from [yegor256/takes](https://github.com/yegor256/takes). How should I proceed to close this ticket then?

**Comment by CarlosGines** [comment] 2016-02-27 14:41
@karato I created an issue for this specific case: yegor256/takes#626
It seems like yegor256/takes#254 did not solve it. This task should be postponed until it is solved in takes. Can you confirm this please?

**Comment by karato** [comment] 2016-03-01 09:12
> @karato It looks like this issue comes from [yegor256/takes](https://github.com/yegor256/takes). How should I proceed to close this ticket then?

@carlosgines you can just wait, it's an impediment

**Comment by karato** [comment] 2016-03-01 09:12
> @karato I created an issue for this specific case: yegor256/takes#626
> It seems like yegor256/takes#254 did not solve it. This task should be postponed until it is solved in takes. Can you confirm this please?

@carlosgines sure, thanks for telling me, take your time

**Comment by CarlosGines** [comment] 2016-03-07 12:34
@mkordas @karato since this task is not going to involve developing for netbout, but for takes, couldn't we close it??

**Comment by mkordas** [comment] 2016-03-07 15:58
@dmzaytsev please make decision here

**Comment by dmzaytsev** [comment] 2016-03-07 17:07
@CarlosGines @mkordas the issue in Netbout not fixed yet so we can't close this ticket

@CarlosGines did you try [latest](https://github.com/yegor256/takes/releases/tag/0.32.4) Takes?

**Comment by dmzaytsev** [comment] 2016-03-07 17:18
@CarlosGines on the side note if it bug in Takes you should submit a bug there 
and put a link to the approved bug here 
like this `@karato we are waiting for yegor256/takes#99999`

you have been assigned 15 days ago so  I would suggest ask PM for more time or put a link to the blocking ticket

**Comment by CarlosGines** [comment] 2016-03-07 17:56
@dmzaytsev yes, I tested with the latest Takes. And I also posted a link to the issue several comments ago (yegor256/takes#626).

I understand that this ticket is not closed, but then it is a waste of time having it assigned to anybody. Developers have a max number of simultaneous tasks, and while this one is blocked, it is also blocking me from working in another ticket.

I think it would be a good idea to be able to free developers while the task is blocked.

**Comment by dmzaytsev** [comment] 2016-03-07 18:05
@CarlosGines feel free submit your idea to https://github.com/teamed/xdsd

**Comment by CarlosGines** [comment] 2016-04-17 21:42
@karato this bug has been fixed on yegor256/takes#626, can this ticket be closed now?

**Comment by karato** [comment] 2016-04-21 12:53
> @karato this bug has been fixed on yegor256/takes#626, can this ticket be closed now?

@carlosgines you should ask bug reporter

**Comment by CarlosGines** [comment] 2016-04-21 13:20
@karato that is true, thank you.

**Comment by CarlosGines** [comment] 2016-04-21 13:21
@mkordas this bug has been fixed on yegor256/takes#626, can you please close this ticket? Thanks in advance.

**Comment by karato** [comment] 2016-04-21 14:28
> @karato that is true, thank you.

@carlosgines sure, you are welcome

**Closed** 2016-04-21 15:18 UTC
Labels: 30 mins, @carlosgines, bug, DEV

**Comment by karato** [comment] 2016-04-22 19:16
@ypshenychka review this ticket please, for compliance with our [quality rules](http://at.teamed.io/qa.html)

**Comment by CarlosGines** [comment] 2016-05-09 22:07
@ypshenychka please help us with the review.

**Comment by ypshenychka** [comment] 2016-05-10 06:51
@karato Quality is bad here since no PR (and correspondingly no work) was done in scope of this issue.

**Comment by karato** [comment] 2016-05-17 11:04
> @karato Quality is bad here since no PR (and correspondingly no work) was done in scope of this issue.

@ypshenychka thanks for review, we'll try to make it better next time

**Comment by karato** [comment] 2016-05-17 15:11
@carlosgines 10 mins was added to the account of @ypshenychka (for QA review), in transaction 86999366
