### ISSUE TITLE
2.23

### ISSUE THREAD

**Issue by karato** [yegor256/netbout#848] opened 2015-12-08 14:35 UTC
Please, publish a new release **2.23** (or higher). Don't forget to update us here regularly (at least once a week), as explained in [this article](http://www.yegor256.com/2015/05/11/software-architect-responsibilities.html).

**Comment by karato** [comment] 2015-12-08 14:43
@dmzaytsev do this task

**Comment by karato** [comment] 2015-12-08 17:15
@dmzaytsev there is no milestone yet, so I set it to `3.1`

**Comment by karato** [comment] 2015-12-12 21:04
@dmzaytsev there are some issues (see [par.33](http://at.teamed.io/policy.html#33)) in the project now:

 * some tasks are stuck: #737 (154 days), #750 (138 days), #761 (116 days), #758 (116 days), #767 (113 days), #770 (111 days), #775 (109 days), #787 (87 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #835, #796. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+970](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-01-20 20:03
@yegor256 I'm going to release a new Markdown implementation, 
a lot of bugs fixed as well
let me know if it works for you

**Comment by karato** [comment] 2016-01-21 12:41
@dmzaytsev please, pay attention to this ([par.33](http://at.teamed.io/policy.html#33)):

 * some tasks in the project are "stuck": #775 (148 days), #801 (113 days), #803 (107 days), #806 (103 days), #805 (103 days), #813 (97 days), #816 (96 days), #817 (95 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #931, #929, #851. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, either close them or update due dates.

-25 added to your rating, at the moment it is: [+2185](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-01-23 06:06
@yegor256 can we release ?

> dmzaytsev commented 2 days ago
> @yegor256 I'm going to release a new Markdown implementation, 
> a lot of bugs fixed as well
> let me know if it works for you

**Comment by karato** [comment] 2016-01-25 16:30
@dmzaytsev There are a few problems in the project now, see [par.33](http://at.teamed.io/policy.html#33):

 * some tasks in the project are "stuck": #775 (152 days), #801 (117 days), #803 (111 days), #806 (107 days), #813 (102 days), #816 (100 days), #817 (99 days), #826 (87 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * these issues are still not dispatched anyhow: #936, #931, #851. Either register as bugs or ask their reporters to close.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+2635](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-01-29 19:32
@dmzaytsev there are some issues (see [par.33](http://at.teamed.io/policy.html#33)) in the project now:

 * some tasks in the project are "stuck": #775 (157 days), #801 (121 days), #803 (115 days), #806 (112 days), #813 (106 days), #816 (105 days), #817 (104 days), #826 (91 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * these issues are still not dispatched anyhow: #936, #931, #851. Either register as bugs or ask their reporters to close.

 * some milestones are due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, either close them or update due dates.

-25 added to your rating, at the moment it is: [+2840](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-02-03 05:35
@yegor256 can we release?

> dmzaytsev commented 11 days ago
> @yegor256 can we release ?
> 
> dmzaytsev commented 2 days ago
> @yegor256 I'm going to release a new Markdown implementation, 
> a lot of bugs fixed as well
> let me know if it works for you

**Comment by yegor256** [comment] 2016-02-03 05:53
@dmzaytsev yes, let's do it

**Comment by dmzaytsev** [comment] 2016-02-03 06:02
@rultor release, tag=`2.23`

**Comment by dmzaytsev** [comment] 2016-02-03 07:14
@yegor256 it seems something wrong `${coveralls.token}`
if so could you fix it ?
I have no access to `settings.xml`

**Comment by yegor256** [comment] 2016-02-03 21:26
@dmzaytsev fixed, try again

**Comment by dmzaytsev** [comment] 2016-02-04 03:53
@rultor release, tag=`2.26`

**Comment by dmzaytsev** [comment] 2016-02-04 04:09
@yegor256 another error `Caused by: java.io.IOException: No coverage report files found`

**Comment by yegor256** [comment] 2016-02-04 05:12
@dmzaytsev this time this has nothing to do with me :) it's a bug inside the project

**Comment by dmzaytsev** [comment] 2016-02-04 05:26
@yegor256 thanks

**Comment by karato** [comment] 2016-02-04 10:37
@dmzaytsev pay attention to the following, as required in [par.33](http://at.teamed.io/policy.html#33):

 * some tasks in the project are "stuck": #775 (162 days), #801 (126 days), #803 (120 days), #806 (117 days), #813 (111 days), #816 (110 days), #817 (108 days), #826 (96 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #981, #936, #931. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+2936](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-02-04 10:46
@yegor256 can we make this release final?

**Comment by karato** [comment] 2016-02-08 15:23
@dmzaytsev pay attention to the following, as required in [par.33](http://at.teamed.io/policy.html#33):

 * some tasks are stuck: #775 (166 days), #801 (131 days), #803 (125 days), #806 (121 days), #813 (115 days), #816 (114 days), #817 (113 days), #826 (101 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #983, #936, #931. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, either close them or update due dates.

-25 added to your rating, at the moment it is: [+3063](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-02-12 17:55
@dmzaytsev please, pay attention to this ([par.33](http://at.teamed.io/policy.html#33)):

 * some tasks are stuck: #775 (171 days), #801 (135 days), #803 (129 days), #806 (126 days), #813 (120 days), #816 (119 days), #817 (117 days), #826 (105 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #983, #936, #931. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

added -25 to your rating, now it is equal to [+3068](http://www.netbout.com/b/35166?open=rating)

**Comment by yegor256** [comment] 2016-02-14 00:15
@dmzaytsev when are you planning to release it?

**Comment by dmzaytsev** [comment] 2016-02-14 05:22
@yegor256 it released 10 days ago. I have asked you to make it final

**Comment by yegor256** [comment] 2016-02-16 04:57
@dmzaytsev I don't think it was released... the latest release is 2.22: https://github.com/yegor256/netbout/releases

**Comment by karato** [comment] 2016-02-18 20:15
@dmzaytsev pay attention to the following, as required in [par.33](http://at.teamed.io/policy.html#33):

 * some tasks are stuck: #775 (175 days), #801 (140 days), #803 (134 days), #806 (130 days), #813 (124 days), #816 (123 days), #817 (122 days), #826 (110 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * these issues are still not dispatched anyhow: #1001, #994, #983, #936, #931. Either register as bugs or ask their reporters to close.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, current score is: [+3233](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-02-23 08:55
@yegor256  could you set final tag for 2.22.4 ?

**Comment by karato** [comment] 2016-02-25 17:20
@dmzaytsev pay attention to the following, as required in [par.33](http://at.teamed.io/policy.html#33):

 * some tasks in the project are "stuck": #775 (182 days), #828 (115 days), #834 (102 days), #839 (98 days), #841 (97 days), #853 (74 days), #852 (74 days), #858 (73 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1001, #983. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+3437](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-02-29 20:36
@dmzaytsev pay attention to the following, as required in [par.33](http://at.teamed.io/policy.html#33):

 * some tasks are stuck: #775 (188 days), #834 (108 days), #839 (104 days), #841 (103 days), #853 (80 days), #852 (80 days), #849 (77 days), #879 (74 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * these issues are still not dispatched anyhow: #1044, #1033, #1001, #983. Either register as bugs or ask their reporters to close.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, current score is: [+3675](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-03-05 18:43
@dmzaytsev pay attention to the following, as required in [par.33](http://at.teamed.io/policy.html#33):

 * some tasks are stuck: #775 (192 days), #834 (112 days), #839 (108 days), #841 (107 days), #879 (78 days), #1003 (23 days), #1008 (20 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1056, #1053, #1044, #1033, #1001, #983. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, current score is: [+3829](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-04-06 12:34
@yegor256 could you mark the latest release 2.22.18 as final ?

**Comment by yegor256** [comment] 2016-04-12 21:37
@karato release 2.22.18 is final

**Comment by karato** [comment] 2016-04-13 09:17
> @karato release 2.22.18 is final

@yegor256 I dropped "draft" flag for release 2.22.18

**Comment by karato** [comment] 2016-04-22 17:02
@dmzaytsev There are a few problems in the project now, see [par.33](http://at.teamed.io/policy.html#33):

 * some tasks are stuck: #754 (alive for 256 days, assigned for 42 days), #775 (241 days), #841 (156 days), #855 (132 days), #1003 (71 days), #1008 (69 days), #1028 (63 days), #1019 (61 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * these issues are still not dispatched anyhow: #1108, #1092, #1089, #1088, #1084, #1082, #1077, #1075. Either register as bugs or ask their reporters to close.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 to your rating, your total score is [+1906](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-04-26 18:15
@yegor256 the last release marked as final 2 week ago
could you check why this ticket not closed yet?

**Comment by karato** [comment] 2016-04-26 19:23
@dmzaytsev There are a few problems in the project now, see [par.33](http://at.teamed.io/policy.html#33):

 * some tasks in the project are "stuck": #775 (245 days), #841 (160 days), #1003 (75 days), #1008 (73 days), #1028 (67 days), #1019 (65 days), #1026 (62 days), #1047 (62 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1108, #1092, #1089, #1088, #1084, #1082, #1077, #1075. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+1481](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-04-30 21:24
@dmzaytsev please, pay attention to this ([par.33](http://at.teamed.io/policy.html#33)):

 * some tasks are stuck: #775 (249 days), #841 (164 days), #1003 (79 days), #1008 (77 days), #1028 (71 days), #1019 (70 days), #1026 (67 days), #1047 (66 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1108, #1092, #1089, #1088, #1084, #1082, #1077, #1075. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+1435](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-05-05 11:15
@dmzaytsev there are some issues (see [par.33](http://at.teamed.io/policy.html#33)) in the project now:

 * some tasks in the project are "stuck": #754 (alive for 269 days, assigned for 12 days), #775 (253 days), #841 (168 days), #855 (144 days), #1003 (84 days), #1008 (81 days), #1028 (75 days), #1019 (74 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1108, #1092, #1089, #1088, #1084, #1082, #1077, #1075. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 to your rating, your total score is [+1344](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-05-06 06:38
@yegor256 the latest release marked as final more than 3 weeks ago!
why this ticket still open?
could you check please?

**Comment by karato** [comment] 2016-05-09 16:07
@dmzaytsev There are a few problems in the project now, see [par.33](http://at.teamed.io/policy.html#33):

 * some tasks in the project are "stuck": #754 (alive for 273 days, assigned for 16 days), #775 (257 days), #841 (173 days), #855 (149 days), #1003 (88 days), #1008 (86 days), #1028 (80 days), #1019 (78 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * these issues are still not dispatched anyhow: #1108, #1092, #1089, #1088, #1084, #1082, #1077, #1075. Either register as bugs or ask their reporters to close.

 * some milestones are due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, either close them or update due dates.

-25 added to your rating, at the moment it is: [+1274](http://www.netbout.com/b/35166?open=rating)

**Comment by dmzaytsev** [comment] 2016-05-13 05:25
@karato why you don't close this ticket ?
it  has been marked as final  a month ago

**Comment by karato** [comment] 2016-05-16 10:37
> @karato why you don't close this ticket ?
> it  has been marked as final  a month ago

@dmzaytsev once a new (not pre) release is published I will close it, not earlier

**Comment by dmzaytsev** [comment] 2016-05-16 11:17
@karato @yegor256  we have a final release from 13 April
I didn't get why I should ask to close the ticket again and again. 3 month!

> karato commented on 13 Apr
@karato release 2.22.18 is final
@yegor256 I dropped "draft" flag for release 2.22.18

**Comment by karato** [comment] 2016-05-20 16:29
@dmzaytsev There are a few problems in the project now, see [par.33](http://at.teamed.io/policy.html#33):

 * some tasks in the project are "stuck": #754 (alive for 284 days, assigned for 27 days), #775 (268 days), #841 (184 days), #855 (alive for 160 days, assigned for 10 days), #1003 (99 days), #1008 (97 days), #1028 (91 days), #1019 (89 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1092, #1089, #1088, #1084, #1082, #1077, #1075, #1064. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, either close them or update due dates.

-25 to your rating, your total score is [+991](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-05-24 19:52
@dmzaytsev please, pay attention to this ([par.33](http://at.teamed.io/policy.html#33)):

 * some tasks are stuck: #754 (alive for 289 days, assigned for 31 days), #775 (273 days), #841 (188 days), #855 (alive for 164 days, assigned for 14 days), #1003 (103 days), #1008 (101 days), #1028 (95 days), #1019 (93 days); please do something about it. There are basically three options: 1) mark some of them as "postponed" (see [par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them (see [par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * these issues are still not dispatched anyhow: #1092, #1089, #1088, #1084, #1082, #1077, #1075, #1064. Either register as bugs or ask their reporters to close.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, current score is: [+807](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-05-29 09:44
@dmzaytsev There are a few problems in the project now, see [par.33](http://at.teamed.io/policy.html#33):

 * some tasks in the project are "stuck": #754 (alive for 293 days, assigned for 36 days), #775 (277 days), #841 (192 days), #855 (alive for 168 days, assigned for 18 days), #1003 (108 days), #1008 (105 days), #1028 (99 days), #1019 (98 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1092, #1089, #1088, #1084, #1082, #1077, #1075, #1064. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * there are some milestones with missed dates: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+629](http://www.netbout.com/b/35166?open=rating)

**Comment by yegor256** [comment] 2016-06-27 20:50
@dmzaytsev let's release 2.23 and make it final, that will be enough to close this ticket. sorry about the delay!

**Comment by dmzaytsev** [comment] 2016-06-28 09:55
@rultor release, tag=`2.23`

**Comment by karato** [comment] 2016-06-28 12:04
@dmzaytsev There are a few concerns (see [par.33](http://at.teamed.io/policy.html#33)):

 * some tasks in the project are "stuck": #754 (alive for 323 days, assigned for 66 days), #775 (307 days), #841 (222 days), #855 (198 days), #1003 (138 days), #1008 (135 days), #1028 (129 days), #1019 (128 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * these issues are still not dispatched anyhow: #1092, #1089, #1088, #1084, #1082, #1077, #1075, #1064. Either register as bugs or ask their reporters to close.

 * some milestones are due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, either close them or update due dates.

added -25 to your rating, now it is equal to [+379](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-07-02 14:38
@dmzaytsev There are a few concerns (see [par.33](http://at.teamed.io/policy.html#33)):

 * some tasks in the project are "stuck": #754 (alive for 327 days, assigned for 70 days), #775 (311 days), #841 (227 days), #855 (203 days), #1003 (142 days), #1008 (140 days), #1028 (134 days), #1019 (132 days); please do something about it ASAP. You basically have three options: 1) mark some of them as "postponed" ([par.26](http://at.teamed.io/policy.html#26)), 2) re-assign them ([par.29](http://at.teamed.io/policy.html#29)), or 3) try to help their performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1092, #1089, #1088, #1084, #1082, #1077, #1075, #1064. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 to your rating, your total score is [+354](http://www.netbout.com/b/35166?open=rating)

**Comment by karato** [comment] 2016-07-06 17:17
@dmzaytsev there are a few issues by [par.33](http://at.teamed.io/policy.html#33):

 * some tasks are stuck: #754 (alive for 332 days, assigned for 74 days), #775 (316 days), #841 (231 days), #855 (207 days), #1003 (146 days), #1008 (144 days), #1028 (138 days), #1019 (136 days); please resolve this. You have three options: 1) mark some of them as "postponed", 2) re-assign them, or 3) help performers to resolve them.

 * some issues were reported some time ago, but still not dispatched: #1092, #1089, #1088, #1084, #1082, #1077, #1075, #1064. Please, do something about them. Either register as bugs or ask their reporters to close them.

 * some milestones are already due: [3.0](https://api.github.com/repos/yegor256/netbout/milestones/1), [3.1](https://api.github.com/repos/yegor256/netbout/milestones/2). Please, do something about it.

-25 added to your rating, at the moment it is: [+314](http://www.netbout.com/b/35166?open=rating)

**Closed** 2024-01-22 12:39 UTC
Labels: 30 mins, ARC, @dmzaytsev
