### ISSUE TITLE
java.lang.IndexOutOfBoundsException: No group 3

### ISSUE THREAD

**Issue by yegor256** [yegor256/netbout#986] opened 2016-02-03 07:15 UTC
I'm getting this sometimes:

```
java.lang.IndexOutOfBoundsException: No group 3
	at java.util.regex.Matcher.start(Matcher.java:374)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:831)
	at com.netbout.rest.MarkdownTxtmark.makeLineBreak(MarkdownTxtmark.java:98)
	at com.netbout.rest.MarkdownTxtmark.html(MarkdownTxtmark.java:63)
	at com.netbout.rest.Markdown$Default.html(Markdown.java:66)
	at com.netbout.rest.bout.XeAttachment$1.toXembly(XeAttachment.java:127)
	at org.takes.rs.xe.XeWhen$1.toXembly(XeWhen.java:57)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeChain$1.toXembly(XeChain.java:63)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeAppend$1.toXembly(XeAppend.java:73)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
	at org.takes.rs.xe.XeWrap.toXembly(XeWrap.java:57)
```

Didn't have in the previous version. The bug is rather annoying!

**Comment by dmzaytsev** [comment] 2016-02-03 08:05
@karato valid bug

**Comment by dmzaytsev** [comment] 2016-02-03 08:10
@yegor256 could you provide an example of the entered text ?

**Comment by dmzaytsev** [comment] 2016-02-03 09:13
@karato assign me please

**Comment by dmzaytsev** [comment] 2016-02-03 09:38
@rultor release, tag=`2.24`

**Comment by dmzaytsev** [comment] 2016-02-03 10:16
@yegor256  I caught  the exception as workaround. @essobedo was be able to open  the bout (see #987),
however I can't reproduce the bug
please share [the error logs](https://github.com/yegor256/netbout/pull/988/files#diff-1021c23d59dcc0efbfc07027c961701eR107) with the text that causes the exception

**Comment by yegor256** [comment] 2016-02-03 13:44
@dmzaytsev I don't see the stack trace any more

**Comment by yegor256** [comment] 2016-02-03 13:45
@dmzaytsev the log:

```
[ERROR] 99ac0c1 com.netbout.rest.MarkdownTxtmark: text @yegor256 I will agree on $35 per hour, in case there won't be any penalties for using short cuts to common operations and for creating API that simplifies writing code(i.e. creating utilities classes that do "more than one thing").    Here is explanation why this approach is proven:      Files.readAllBytes(Paths.get("/path/to/file");//from java nio  and   FileUtils.readFileToByteArray(fileName);//from apache io commons    Is much easier to read and it less error prone in comparison to  "correct" way of using classes that do "only one task:  try {          fin = new FileInputS...
Feb 03 14:40:23 www.netbout.com ...tream(new:  File("/path/to/FILE"));          ch = fin.getChannel();          int size = (int) ch.size();          MappedByteBuffer buf = ch.map(MapMode.READ_ONLY, 0, size);          byte[] bytes = new byte[size];          buf.get(bytes);      } finally {          try {              if (fin != null) {                  fin.close();              }              if (ch != null) {                  ch.close();              }          }      }    Since InputStream,OutputStream classes are in Java since 1.0 and NIO Files are since 1.7 - it turned out that developers are not satisfied with classes "doing only one thing" as well. causes No group 3 
```

**Comment by dmzaytsev** [comment] 2016-02-03 15:45
@karato please see PR #990

**Comment by karato** [comment] 2016-02-03 15:55
> @karato valid bug

@dmzaytsev tagged this issue with "bug"

**Comment by dmzaytsev** [comment] 2016-02-03 17:36
@rultor release, tag=`2.25`

**Comment by karato** [comment] 2016-02-04 10:19
@yegor256 since the ticket has no milestone I set it to 3.1

**Comment by dmzaytsev** [comment] 2016-02-04 10:34
@karato assign me please

**Comment by karato** [comment] 2016-02-04 12:21
> @karato assign me please

@dmzaytsev the task is yours, please proceed

**Comment by karato** [comment] 2016-02-04 12:21
> @karato please see PR #990

@dmzaytsev will take a look, thanks

**Comment by karato** [comment] 2016-02-04 12:21
> @karato assign me please

@dmzaytsev sure, it was yours before, go ahead

**Comment by karato** [comment] 2016-02-04 12:37
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-6585a348`

**Comment by dmzaytsev** [comment] 2016-02-04 12:39
@yegor256 fixed in #990 please close the ticket

**Comment by dmzaytsev** [comment] 2016-02-05 06:28
@yegor256 ping

**Comment by dmzaytsev** [comment] 2016-02-06 17:38
@yegor256 ping

**Comment by dmzaytsev** [comment] 2016-02-08 16:23
@yegor256 fixed in #990 please close the ticket

**Comment by dmzaytsev** [comment] 2016-02-11 05:23
@karato I need more time

**Comment by karato** [comment] 2016-02-11 12:10
> @karato I need more time 

@dmzaytsev no problem, thanks for letting me know

**Comment by dmzaytsev** [comment] 2016-02-18 05:23
@yegor256 fixed in #990 please close the ticket

**Closed** 2016-02-19 23:16 UTC
Labels: 30 mins, @dmzaytsev, bug, DEV

**Comment by karato** [comment] 2016-02-22 15:01
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment] 2016-02-22 15:04
@karato Quality is good.

**Comment by karato** [comment] 2016-02-22 18:58
> @karato Quality is good.

@ypshenychka thank you, good quality is always good ;)

**Comment by karato** [comment] 2016-02-22 19:14
@dmzaytsev I added 10 mins to @ypshenychka (for QA review) in transaction 78316429. Much obliged! I have added **30 mins** to your account in payment "78316438", 390 hours and 20 mins spent. +30 added to your rating, at the moment it is: [+3392](http://www.netbout.com/b/35166?open=rating)
