### ISSUE TITLE
Not possible to remove user from bout

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/netbout#633] opened 2015-05-25 01:05 UTC
If user name is larger than icon size, this is not possible to click "X" to remove user from bout. You will be able to remove only most right person, but not first or in the middle.
![screenshot](https://cloud.githubusercontent.com/assets/861305/7790496/de92309a-028a-11e5-82ba-2821b515b0d4.png)

**Comment by dmzaytsev** [comment] 2015-05-25 05:10
@ikhvostenkov isn't it a duplicate of #528 ?

**Comment by ikhvostenkov** [comment] 2015-05-25 08:13
@dmzaytsev True, this is the same, did not see this when posted my. Can be marked as duplicated.

**Comment by dmzaytsev** [comment] 2015-05-25 08:19
@ikhvostenkov just close this issue
thanks

**Comment by ikhvostenkov** [comment] 2015-05-25 16:00
@dmzaytsev closed.

**Closed** 2015-05-25 16:00 UTC
