### ISSUE TITLE
Application Error during access to some pages

### ISSUE THREAD

**Issue by YamStranger** [yegor256/netbout#588] opened 2015-04-24 12:19 UTC
@yegor256
Problem:
 If user tries to get access to pages without rights to access them, he receives "Application Error". Application must never return errors to user. 
Solution:
 In this situation application must return to him page with correct explanation, not error. For example "We have no page you are looking for" or http://stackoverflow.com/questionsMy

Please look at image.
![application error](https://cloud.githubusercontent.com/assets/1667699/7318468/e1cc2634-ea94-11e4-8039-f765ab02daa3.JPG)

**Comment by karato** [comment] 2015-04-27 08:57
@yamstranger I am aware of the task, give me some time to find a developer...

**Comment by karato** [comment] 2015-04-27 09:01
@yamstranger thanks for reporting! I topped your account for 15 mins, transaction 56032529

**Comment by yegor256** [comment] 2015-05-11 01:32
it's fixed already

**Comment by YamStranger** [comment] 2015-05-17 09:30
@yegor256 This issue is not fixed. 
Now I can find null pointers. 
![nullpointer](https://cloud.githubusercontent.com/assets/1667699/7669825/7f7d4c2a-fc90-11e4-960f-17dcaf65cc48.JPG)

**Comment by yegor256** [comment] 2015-05-18 02:16
@YamStranger thanks, reopening...

**Comment by karato** [comment] 2015-05-19 19:16
@yamstranger I set milestone here to `3.1`, let me know if it is wrong

**Comment by YamStranger** [comment] 2015-05-20 06:23
@karato have you a link about meaning of "milestone" on such projects?

**Comment by yegor256** [comment] 2015-05-20 17:26
@YamStranger milestones are here: https://github.com/yegor256/netbout/milestones

**Comment by karato** [comment] 2015-06-08 10:28
@erimerturk this is your task

**Comment by erimerturk** [comment] 2015-06-13 21:33
@YamStranger how can i reproduce bug ? i couldn't find it. thank you

**Comment by YamStranger** [comment] 2015-06-14 07:02
@erimerturk. To reproduce bug you need find at this project on github some closed issue, with payement info. Here will be something like " added +30 to your rating, now it is equal to +106", and +106 is reference to netbout. Or you can generate some url like "http://www.netbout.com/b/35267?;lkjl;kj=kjhkh". When I created this bug - after such redirection I find null pointer, but now I see only "page not found". So I can not reproduce this bug.

**Comment by erimerturk** [comment] 2015-06-14 07:08
@YamStranger could we say it is fixed ? @karato what do you think ?

**Comment by YamStranger** [comment] 2015-06-14 07:28
@erimerturk As for me it should be beautiful, like first page and with message "page not found". Now it looks like "hot fix". But it up to you. "null pointer" is fixed, yes.

**Comment by erimerturk** [comment] 2015-06-14 17:13
@dmzaytsev @yegor256 what do you think ? Do we need this page ? What about page design ?

**Comment by dmzaytsev** [comment] 2015-06-14 18:17
@erimerturk I think will be enough to open the root page and to print a status message "page not found" instead "new bout started" like on the screenshot below

![image](https://cloud.githubusercontent.com/assets/9972909/8149815/3e69bbe4-12eb-11e5-8019-178c08110ff9.png)

if user not logged in, just open the root page

**Comment by erimerturk** [comment] 2015-06-14 18:41
@yegor256 please fix your comment which is 

###### yegor256 commented on May 11
###### it's fixed already

According to our [quality rules] (http://www.teamed.io/qa.html): 

###### Messages in a ticket always start with a name of a user they are addressed to.

**Comment by erimerturk** [comment] 2015-06-18 15:10
@karato Could you, please, assign someone else or postpone this task until 25th of June, I will be out until this for personal reasons?

**Comment by yegor256** [comment] 2015-06-19 00:24
@erimerturk fixed

**Comment by dmzaytsev** [comment] 2015-06-21 04:42
@karato FYI

> erimerturk commented 3 days ago
> @karato Could you, please, assign someone else or postpone this task until 25th of June, I will be out until this for personal reasons?

**Comment by karato** [comment] 2015-06-23 11:26
@erimerturk 15 days already, in 48 hours I will re-assign... added -30 to your rating, now it is equal to [+120](http://www.netbout.com/b/35280?open=rating)

**Comment by erimerturk** [comment] 2015-06-23 11:38
@karato i have already send you message 5 days ago, please see it. @dmzaytsev send you reminder . why is it happening ? i am not able to work and said it before to you. could you please undo negative rate ?

**Comment by erimerturk** [comment] 2015-06-23 11:47
@karato see also #692 last message

**Comment by yegor256** [comment] 2015-06-23 16:17
@karato indeed, assign someone else here

**Comment by yegor256** [comment] 2015-06-23 16:17
@erimerturk I'll fix the rating

**Comment by karato** [comment] 2015-06-23 17:47
> @karato indeed, assign someone else here

@yegor256 I deducted 30 points from your rating

**Comment by karato** [comment] 2015-06-23 17:47
> @karato indeed, assign someone else here

@yegor256 I will try to find someone else

**Comment by karato** [comment] 2015-09-03 20:13
@mstzn36 this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions; The budget here is **30 mins**, which is exactly how much time will be paid for, when the task is [completed](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by karato** [comment] 2015-09-21 17:33
@hs3180 can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by karato** [comment] 2015-10-07 11:19
@hs3180 you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. -30 added to your rating, current score is: [-142](http://www.netbout.com/b/35610?open=rating)

**Comment by hs3180** [comment] 2015-10-09 08:00
@yegor256 
I've started a snapshot `netbout-web` server.
The first user named `tester` opens a new bout which id is `1444377065085`.
register a new user named `alex`, and accesss this address : `http://localhost:8888/b/1444377065085`.
`netbout` gives me **page not found**.
![image](https://cloud.githubusercontent.com/assets/1643451/10388700/af0a1790-6e9e-11e5-96de-cdc7818b0ddd.png)

I think this issue was fixed already.

**Comment by dmzaytsev** [comment] 2015-10-09 08:08
@hs3180 take a look this comment https://github.com/yegor256/netbout/issues/588#issuecomment-111860194
the browser should be redirected to root page in case of such errors
"page not found" should be displayed like message on screenshot in the comment

**Comment by karato** [comment] 2015-10-13 09:22
@hs3180 this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle; -60 to your rating, your total score is [-172](http://www.netbout.com/b/35610?open=rating)

**Comment by karato** [comment] 2015-10-18 19:32
@bdragan please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here... Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dmzaytsev** [comment] 2015-10-31 16:10
@bdragan just a suggestion
ask the PM for more time if you working on a ticket more than 7 days
otherwise your rating will be decreased, see the policy
but yes it's a campus project, usually you have about 14 days before you get a warning from the PM

**Comment by bdragan** [comment] 2015-10-31 19:50
@dmzaytsev Noted, thanks!

**Comment by karato** [comment] 2015-11-03 11:48
@bdragan 15 days already, in 48 hours I will re-assign... -30 added to your rating, current score is: [+203](http://www.netbout.com/b/35709?open=rating)

**Comment by dmzaytsev** [comment] 2015-11-03 15:33
@karato we need more time here

**Comment by karato** [comment] 2015-11-03 16:51
> @karato we need more time here

@dmzaytsev OK, take your time

**Comment by bdragan** [comment] 2015-11-03 20:14
@YamStranger PR #829 has been merged to master. The issue can be closed.

**Closed** 2015-11-03 20:52 UTC
Labels: 30 mins, @bdragan, bug, DEV

**Comment by karato** [comment] 2015-11-05 13:22
@ypshenychka please, check this issue for QA compliance, as per [par.24](http://www.teamed.io/policy.html#24)

**Comment by ypshenychka** [comment] 2015-11-05 15:43
@karato Quality is good.

**Comment by ypshenychka** [comment] 2015-11-17 07:54
@karato Please consider this ticket. It was already checked and marked as good.

**Comment by ypshenychka** [comment] 2015-11-25 06:17
@yegor256 The performer of the ticket was not yet paid.

**Comment by ypshenychka** [comment] 2016-01-05 13:28
@yegor256 @karato Could you please consider this ticket?

**Comment by yegor256** [comment] 2016-01-05 13:46
@ypshenychka this ticket is remove from the backlog, since it's too old. Can you please raise this concern in some other ticket, which is active now and we'll make a payment from there.

**Comment by ypshenychka** [comment] 2016-01-06 09:01
@yegor256 Mentioned in [ticket #637](https://github.com/yegor256/netbout/issues/637#issuecomment-169270744). Thanks.
