### ISSUE TITLE
error

### ISSUE THREAD

**Issue by preetimanda** [yegor256/netbout#1056] opened 2016-02-28 06:15 UTC
java.lang.IllegalStateException: [GET http://www.netbout.com/?PsByFlag=PsGoogle&code=4%2FqN16biU8kB3xRxwBdEU3IRGvl34ELhqvGtlaIK4A474&state=http%3A%2F%2Fwww.netbout.com%2F] failed in 365ms: null
    at org.takes.facets.fallback.TkFallback.error(TkFallback.java:233)

**Comment by dmzaytsev** [comment] 2016-02-29 10:17
@prahladyeri thanks for reporting 
Actually Google Auth is broken now and we have ticket #1038 for this case

**Comment by dmzaytsev** [comment] 2016-03-07 07:50
@karato this is duplicate of #1038

**Closed** 2024-01-22 12:39 UTC
