### ISSUE TITLE
when reply to a bout message from email, it creates too many bouts

### ISSUE THREAD

**Issue by mstzn36** [yegor256/netbout#758] opened 2015-08-10 22:40 UTC
When i reply to a bout message from email,it creates too many bouts on my main menu.
I think application should handle this case.

Here's some of bouts name : 
#35524 com.netbout.client.RtUserITCase
#35527 com.netbout.client.RtBoutITCase
#35518 com.netbout.client.RtAttachmentsITCase

**Comment by dmzaytsev** [comment] 2015-08-12 11:25
@mstzn36 reply to bout from email not implemented yet.

**Comment by dmzaytsev** [comment] 2015-08-12 11:25
@karato it's a valid bug

**Comment by karato** [comment] 2015-08-17 16:30
> @karato it's a valid bug

@dmzaytsev I tagged this as "bug"

**Comment by karato** [comment] 2015-08-17 18:43
@mstzn36 attached this issue to milestone "3.1" (let me know if this is wrong)

**Comment by karato** [comment] 2015-08-18 21:12
@mstzn36 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-0SL77479T52984116`

**Comment by karato** [comment] 2015-12-09 21:00
@mkordas can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here. This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by mkordas** [comment] 2015-12-10 22:26
> If you have any technical questions, don't hesitate to ask right here.

@karato is it possible to test email feature locally? Right now I'm getting `Sorry we were not able to send verification link to the new address`.

**Comment by dmzaytsev** [comment] 2015-12-11 05:52
@mkordas yes it's possible if you updated the email credentials in `MANIFEST.MF`
but I would suggest to reproduce the issue on the production server before

**Comment by mkordas** [comment] 2015-12-11 22:00
@dmzaytsev unfortunately I cannot reproduce this issue on production instance. When I reply to the email sent by Netbout nothing happens for me. Am I missing something?

**Comment by dmzaytsev** [comment] 2015-12-13 13:13
@mstzn36 we can't reproduce the issue
It seems you have launched integration test on the production instance, that's why these bouts have been created

**Comment by dmzaytsev** [comment] 2015-12-13 14:43
@karato this is invalid

**Comment by karato** [comment] 2015-12-13 16:22
> @karato this is invalid

@dmzaytsev OK, I put "invalid" label here

**Comment by mstzn36** [comment] 2015-12-13 22:25
@dmzaytsev Actually I had faced this issue on production instance. Here's my [homepage] (http://s14.postimg.org/w9bvy6881/Screen_Shot_2015_12_14_at_00_15_52.png)

I tried again but i could not reproduce. 

fyi

**Comment by dmzaytsev** [comment] 2015-12-14 03:53
@mstzn36 so could you close the ticket ?

**Comment by karato** [comment] 2015-12-14 19:09
@mstzn36 I am closing it

**Closed by karato** 2015-12-14 19:09 UTC
Labels: 30 mins, bug, DEV, invalid
