### ISSUE TITLE
Registering for NetBout on mobile is faulty.

### ISSUE THREAD

**Issue by IgorGanapolsky** [yegor256/netbout#1060] opened 2016-03-01 03:30 UTC
After going through registration process with my github credentials, I see a page that is only partly functional.
![screenshot_20160229-222134](https://cloud.githubusercontent.com/assets/201209/13416887/170aa9bc-df34-11e5-9d66-0c7c903dcf4c.png)

**Comment by dmzaytsev** [comment] 2016-03-02 18:45
@IgorGanapolsky 
> I see a page that is only partly functional

please explain a little bit
what do you mean exactly?

**Comment by IgorGanapolsky** [comment] 2016-03-02 18:58
@dmzaytsev Does the top-right section look correct to you?

**Comment by dmzaytsev** [comment] 2016-03-02 19:26
@IgorGanapolsky I woudn't like to guess
do you mean inactive "Start bout" link  or maybe the form looks incorrect on screens with a small resolution or maybe you not be able to set your email or something else.
A future performer of this ticket need to know what exactly he/she should to do.
that's why I have asked you.

**Comment by IgorGanapolsky** [comment] 2016-03-02 19:32
It looks exactly like the screenshot on my Android device: Nexus 5X.  The top-right part is all jumbled up and non-functional.

**Comment by dmzaytsev** [comment] 2016-03-03 04:07
@IgorGanapolsky Actually it is duplicate of #813
you can search for something as workaround for now
just type any text in `Find` area and press Enter
you will be able to start a new bout after that

**Comment by dmzaytsev** [comment] 2016-04-06 14:42
@karato  duplicate of #813

**Closed** 2024-01-22 12:39 UTC
