### ISSUE TITLE
Error trying to go by github issue link

### ISSUE THREAD

**Issue by longtimeago** [yegor256/netbout#666] opened 2015-06-03 18:22 UTC
There's an error appears if clicking on any github issue link from "agenda" page
```java
java.lang.IllegalArgumentException: Illegal character in path at index 25: http://www.netbout.com/b/[https://github.com/jcabi/jcabi-github/pull/1100](https://github.com/jcabi/jcabi-github/pull/1100)
	at java.net.URI.create(URI.java:859)
	at org.takes.misc.Href.(Href.java:73)
	at org.takes.rq.RqHref$Base.href(RqHref.java:72)
	at org.takes.facets.auth.PsByFlag.enter(PsByFlag.java:102)
	at org.takes.facets.auth.PsChain.enter(PsChain.java:72)
	at org.takes.facets.auth.TkAuth.act(TkAuth.java:86)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.forward.TkForward.act(TkForward.java:63)
	at org.takes.facets.fallback.TkFallback.route(TkFallback.java:78)
	at org.takes.facets.fallback.TkFallback.access$000(TkFallback.java:48)
	at org.takes.facets.fallback.TkFallback$1.act(TkFallback.java:60)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.facets.flash.TkFlash.act(TkFlash.java:104)
	at org.takes.tk.TkMeasured$1.act(TkMeasured.java:65)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkVersioned$1.act(TkVersioned.java:70)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWithHeaders$1.act(TkWithHeaders.java:69)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.tk.TkWrap.act(TkWrap.java:59)
	at org.takes.http.BkBasic.print(BkBasic.java:98)
	at org.takes.http.BkBasic.accept(BkBasic.java:76)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Illegal character in path at index 25: http://www.netbout.com/b/[https://github.com/jcabi/jcabi-github/pull/1100](https://github.com/jcabi/jcabi-github/pull/1100)
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.(URI.java:595)
	at java.net.URI.create(URI.java:857)
	... 28 more
```
Looks like the link itself is broken

**Comment by yegor256** [comment] 2015-06-03 23:43
@longtimeago it's a duplicate of #664

**Closed by yegor256** 2015-06-03 23:43 UTC

**Comment by longtimeago** [comment] 2015-06-04 06:30
@yegor256 sorry, it wasn't so clear from bug title
