### ISSUE TITLE
This is possible to remove topic starter from bout

### ISSUE THREAD

**Issue by ikhvostenkov** [yegor256/netbout#634] opened 2015-05-25 01:11 UTC
If I create new bout, anybody who was added to this bout is able to remove me from this bout.

**Comment by dmzaytsev** [comment] 2015-05-25 05:25
@yegor256 what do you think?
Maybe we shoud also add some roles to netbout? For example add an administrator role that can remove anyone from anywhere. We can define members in `/netbout/netbout-web/src/main/resources/META-INF/MANIFEST.MF` or a comand line argument...
`Netbout-Admins: yegor256,alice` or `-Dnetbout.admins="yegor256,alice"`

**Comment by yegor256** [comment] 2015-05-25 05:33
@ikhvostenkov well, this is by design. a "bout" is a communication room, where everybody is equal. anyone can remove you from the bout and anyone can invite you back. maybe this is not intuitive, but that's how it was created. let's discuss how to improve that...

**Comment by dmzaytsev** [comment] 2015-05-25 13:18
@yegor256 @ikhvostenkov I think the bout creator should have a bit more privileges than other
friends.

**Comment by ikhvostenkov** [comment] 2015-05-25 16:08
@dmzaytsev @yegor256 I agree with Dmitry. We can add one more field "Owner" to identify bout creator. In this case we can avoid using roles, actually we do need roles here we just need to identify bout starter.

**Comment by dmzaytsev** [comment] 2015-05-25 17:28
@ikhvostenkov @yegor256 Why I proposed an admin role ? Let's imagine  a situation when  someone has created a bout to discuss some question, but later the owner is no longer engaged this subject. We need to preserve the  messages instead of creation a new bout. In this case an administrator just remove the original owner from the bout and assign a new owner.

**Comment by yegor256** [comment] 2015-05-25 18:20
@dmzaytsev it's a "public" platform, which is supposed to have millions of bouts. We can't have any "admins" here. The platform has to be able to regulate itself. Here is a question - why do we need to remember who was the creator of a bout? What's wrong with giving everybody an ability to remove anybody?

**Comment by dmzaytsev** [comment] 2015-05-25 18:35
@yegor256 I considered it as a communication platform for teamed.io :) anyway 

it's a public platform... in this case we don't need any admins, you're right

well..  let's imagine you have a skype account  whats wrong if anybody can deprive you the account ? no problem you can register a new one and invite your contact list again isn't it?  but it's is not good, right? Do you see my point?

**Comment by yegor256** [comment] 2015-05-25 18:41
@dmzaytsev well, if I remove you from a bout, I don't remove/delete your account. You can join the bout again, if I invite you again. It's just inconvenient for you, but it's not fatal. Let's try to imagine a situation when this removal is a problem... I can't think of any

**Comment by dmzaytsev** [comment] 2015-05-25 18:43
@yegor256 key words is `if I invite you again`
I lost access to some content in the bout. in some cases it can be a valuable

**Comment by yegor256** [comment] 2015-05-25 18:49
@dmzaytsev yes, but if you need it again, I will invite you... or you mean that I can "block" you from some valuable content intentionally, but removing you from the bout? maybe "kicking out" is not a good idea in the first place. maybe we should remove this feature and create a new one - "suspend a participant". you will see the bout, all its messages, but only till the moment you were active in it. all changes that happen after that won't be visible to you. you will see a banner "+45 more messages, but you can't see them"... what do you think?

**Comment by dmzaytsev** [comment] 2015-05-25 18:53
@yegor256 suspend instead kick out
I like this idea

**Comment by dmzaytsev** [comment] 2015-05-26 16:09
@ikhvostenkov @yegor256 so
* we have to  implement the suspend feature
* we have to disable kick out feature, but user should have ability to remove self from the bout 
are you agree?

**Comment by yegor256** [comment] 2015-05-26 16:54
@dmzaytsev I would suggest to remove the "kick-out" feature entirely

**Comment by dmzaytsev** [comment] 2015-05-26 16:57
@yegor256 how to leave the bout in this case ?

**Comment by yegor256** [comment] 2015-05-26 17:03
@dmzaytsev there is no way to "leave". just suspend your participation and you won't see any new messages. but the bout will stay in your inbox, at the bottom. what's wrong about it? why do you need to "leave" it entirely?

**Comment by dmzaytsev** [comment] 2015-05-26 17:08
@yegor256 maybe we need a hide option? allows to hide the suspended bouts.
I wouldn't want to see the hundreds of bouts in my inbox

**Comment by yegor256** [comment] 2015-05-26 17:34
@dmzaytsev the inbox is "endless". you see only the first 10 and then you just scroll down and you see more and more. those that are not updated will stay at the end of the list. you won't see them. they won't bother you at all.

**Comment by dmzaytsev** [comment] 2015-06-14 04:41
@karato it's a valid bug

**Comment by dmzaytsev** [comment] 2015-06-14 04:41
@karato please set milestone to 3.1

**Comment by dmzaytsev** [comment] 2015-06-14 04:43
@ikhvostenkov a future performer should remove the "kick-out"-feature

**Comment by dmzaytsev** [comment] 2015-06-14 05:14
@ikhvostenkov @yegor256 suspend feature will be implemented in  #697

**Comment by karato** [comment] 2015-06-14 09:15
> @karato it's a valid bug

@dmzaytsev I just added bug tag here

**Comment by karato** [comment] 2015-06-14 10:46
@ikhvostenkov I added milestone `3.1` to this issue, let me know if there has to be something else

**Comment by karato** [comment] 2015-06-14 11:37
@ikhvostenkov thanks for reporting! I topped your account for 15 mins, transaction 59119260

**Comment by karato** [comment] 2015-06-14 14:09
> @karato please set milestone to 3.1

@dmzaytsev thanks, I set it to "3.1"

**Comment by dmzaytsev** [comment] 2015-07-14 19:06
@karato please assign this task

**Comment by karato** [comment] 2015-07-16 09:32
> @karato please assign this task

@dmzaytsev we don't have enough people in the project now... we're working on it now

**Comment by dmzaytsev** [comment] 2015-07-16 10:07
@karato  thanks for letting me know

**Comment by karato** [comment] 2015-07-16 18:26
> @karato  thanks for letting me know

@dmzaytsev no problems

**Comment by dmzaytsev** [comment] 2015-07-19 17:36
@karato this is postponed

**Comment by karato** [comment] 2015-07-19 18:54
> @karato this is postponed

@dmzaytsev OK, I put "postponed" label here

**Comment by karato** [comment] 2015-07-19 18:54
> @karato this is postponed

@dmzaytsev got it, someone else will be assigned soon

**Closed** 2024-01-22 12:40 UTC
Labels: bug, 30 mins, DEV, postponed
