### ISSUE TITLE
Tests not running after upgrade to Takes 0.20

### ISSUE THREAD

**Issue by mbarbieri** [yegor256/netbout#669] opened 2015-06-04 21:22 UTC
Trying to upgrade to takes 0.20 lots of tests (just an example ```TkBoutITCase```) are failing because of this exception:
```
java.lang.IllegalArgumentException: header line of HTTP response "HTTP/1.1 200 OK" doesn't match "[a-zA-Z0-9\-]+:\p{Print}+" regular expression, but it should, according to RFC 7230
	at org.takes.rs.RsPrint.printHead(RsPrint.java:137)
	at org.takes.rs.RsPrint.print(RsPrint.java:110)
	at org.takes.http.BkBasic.print(BkBasic.java:99)
	at org.takes.http.BkBasic.accept(BkBasic.java:77)
	at org.takes.http.BkSafe.accept(BkSafe.java:58)
	at org.takes.http.BkTimeable.accept(BkTimeable.java:94)
	at org.takes.http.BkParallel$1.run(BkParallel.java:97)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is blocking #662

**Comment by yegor256** [comment] 2015-06-04 21:52
@dmzaytsev FYI, it's not a bug since it doesn't say what is broken in current master

**Comment by dmzaytsev** [comment] 2015-06-05 18:06
@mbarbieri upgrading to Takes 0.2 is the part of the subject of your ticket(#662) 
if the ticket will be too big for the time budget just upgrade the project to Takes 0.2 in one PR and create a puzzle for other job

**Comment by mbarbieri** [comment] 2015-06-05 18:36
@dmzaytsev actually I've already done the changes for #662 and fixed some tests that were failing because of that. What if I push the code `@Ignore` the failing tests (there are quite a lot) and let someone else fix them?

**Comment by dmzaytsev** [comment] 2015-06-06 06:25
@mbarbieri I answered to you in #662 
please close this issue

**Closed** 2015-06-06 07:41 UTC
